apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mimi-server
  namespace: new-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: kimulia/app:v1.0
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: UUID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
---

apiVersion: v1
kind: Service
metadata:
  name: my-mimi-service
  namespace: new-namespace
spec:
  selector:
    app: app-python
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Namespace
metadata:
  name: new-namespace